# Generated by Django 4.1.13 on 2024-03-22 17:31

import FetchAPP.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeTrafficInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('percentage', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryClassification',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompetidorAux',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=100)),
                ('monthly_views', models.CharField(max_length=100)),
                ('ranking', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('place_1', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CompetidorAux)),
                ('place_2', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CompetidorAux)),
                ('place_3', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CompetidorAux)),
                ('place_4', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CompetidorAux)),
                ('place_5', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CompetidorAux)),
                ('place_6', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CompetidorAux)),
                ('place_7', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CompetidorAux)),
                ('place_8', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CompetidorAux)),
                ('place_9', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CompetidorAux)),
                ('place_10', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CompetidorAux)),
            ],
        ),
        migrations.CreateModel(
            name='CountryClassification',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CountryTrafficInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('country_1', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CountryInfo)),
                ('country_2', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CountryInfo)),
                ('country_3', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CountryInfo)),
                ('country_4', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CountryInfo)),
                ('country_5', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CountryInfo)),
                ('country_6', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CountryInfo)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('site_info', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.SiteInfo)),
                ('traffic_engagement_info', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.TrafficEngagementInfo)),
                ('keywords_info', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.KeywordInfo)),
                ('traffic_by_gender_info', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.GenderTrafficInfo)),
                ('traffic_by_age_info', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.AgeTrafficInfo)),
                ('traffic_by_social_media_info', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.SocialMediaTrafficInfo)),
                ('origin_traffic_info', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.OriginTrafficInfo)),
                ('traffic_by_country_info', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CountryTrafficInfo)),
                ('traffic_sources_info', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.TrafficSourceInfo)),
                ('competitors_info', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.CompetitorInfo)),
                ('target_audience_info', djongo.models.fields.EmbeddedField(model_container=FetchAPP.models.TargetAudienceInfo)),
            ],
        ),
        migrations.CreateModel(
            name='GenderTrafficInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
                ('percentage', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100)),
                ('access_by_keyword', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OriginTrafficInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('percentage', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('site_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaTrafficInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('percentage', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TargetAudienceInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('target_audience', models.CharField(max_length=100)),
                ('main_topics', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficEngagementInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('total_visits', models.CharField(max_length=10)),
                ('bounce_rate', models.CharField(max_length=10)),
                ('pages_per_visit', models.CharField(max_length=10)),
                ('average_visit_duration', models.CharField(max_length=10)),
                ('last_month_changes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSourceInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('percentage', models.CharField(max_length=10)),
            ],
        ),
    ]
